### ISSUE TITLE
[BUG] Players can access chests on arena spawn before start the game

### ISSUE THREAD

**Issue by andris155** [ShaneBeeStudios/HungerGames#52]
**Describe the bug**

Players can access chests on arena spawn before start the game.
Players can take items out of from chests before started the game.

**To Reproduce**

1. Set arena spawnpoint near the spawn chests.
2. Start game, and before started players can access to the chests.

**Expected behavior**

Disable chest opening before game start.

**Screenshots/Errors**

![2020-10-20_18 11 10](https://user-images.githubusercontent.com/8324198/96613778-a63e6700-12ff-11eb-9563-a76036f708b1.png)

**Version Info:**
 - **Plugin Version:** 4.14.0
 - **Server Version/Platform** Paper 1.16.3

**Additional context**

**Comment by ShaneBeee** [comment]
Players shouldn't be able to move before the game starts.
They should be frozen in their spawn location. 
That said, I have heard reports that if the server difficulty is set to PEACEFUL, then this system doesn't work.

What is your world's difficulty on?

**Comment by andris155** [comment]
Yes players can't move. But chests too near spawn location and can access chests without move.

**Comment by ShaneBeee** [comment]
ok good to know, Ill work on something so they cant open chests

**Comment by ShaneBeee** [comment]
Ok, did some testing, I can not replicate this:
<img width="966" alt="Screen Shot 2020-10-21 at 1 35 38 AM" src="https://user-images.githubusercontent.com/20008482/96694834-cbea6100-133d-11eb-8103-c67398378a82.png">

**Comment by Waterman1001** [comment]
I wanted to report the same problem, but I see you already completed it.
Thank you for fixing this problem, hope I can download it soon :) 

For me the reason that people are able to access chests is because by destroying blocks they spawn on they are able to SLIGHTLY move a bit every time they destroy it. That way they are able to move like 1 millimeter a time and get access to the chests. So players are actually frozen but not really since they can move by destroying block they are standing on :S
