### ISSUE TITLE
HungerGames GameListener optimization

### ISSUE THREAD

**Issue by andris155** [ShaneBeeStudios/HungerGames#81]
**Is your feature request related to a problem? Please describe:**

HungerGames Gamelistener currently high CPU usage sometimes when end the HungerGames game.

<img width="917" alt="Screenshot 2021-01-02 203515" src="https://user-images.githubusercontent.com/8324198/103465359-170bf180-4d3b-11eb-879c-b970cd099bf7.png">

**Describe the solution you'd like:**

Optimize HungerGames Gamelistener.

**Comment by ShaneBeee** [comment]
So the issue here is, the GameListener$$Lambda is referring to a scheduler. 
Unfortunately that class has 3 of those, and the timings does not tell me which one is causing that tick issue.
If you could send me a link to the timings, I can maybe investigate this a little further.

**Comment by andris155** [comment]
https://timings.aikar.co/?id=2d0eed56d68a442eaec68ec192ecebbd#plugins

<img width="276" alt="Screenshot 2021-01-03 230148" src="https://user-images.githubusercontent.com/8324198/103489844-ab4b8680-4e17-11eb-8a37-da3989d798bc.png">

**Comment by ShaneBeee** [comment]
Ok, viewing this closer, I don't think this is actually an issue.
If im reading the timings correctly, im going to assume this is caused when a player dies in a game. 
When that happens a LOT of things are processed in that scheduler, including managing the death message, healing the player, restoring inventory, TPing them out of the arena (which involves world/chunk loads), etc. 
That said, if you look at HG in the timings, its doing quite well (see circled part)
<img width="1533" alt="Screen Shot 2021-01-03 at 2 08 15 PM" src="https://user-images.githubusercontent.com/20008482/103489940-32274180-4dcd-11eb-8f0e-33cb8f580d95.png">

I think the way the timings are setup, it just looks bad for that red part, when in fact its actually not, its just caused by a lot of things happening at that one time.

**Comment by andris155** [comment]
So this unfortunately cannot be optimized? :(

**Comment by ShaneBeee** [comment]
I don't think its actually unoptimized, it just looks like it. 
Aikar's timings sometimes makes things look bad, when in reality they're not. 
From what I can see in your timings, you are running **A LOT** of plugins for one server. Often times, when a plugin does one thing, it may trigger other plugins to interact as well, which in turn makes a LOT happen at once, and at the same time, make the timings look bad.

**Comment by andris155** [comment]
Thanks for the information. I will remove some plugins.
